pub(crate) mod admin;
pub mod auth;
pub mod dns_cache;
mod fallback;
mod handlers;
pub mod http_client;
pub(crate) mod kiro_handlers;
pub mod kiro_state;
pub mod ip_filter;
pub mod metrics;
pub(crate) mod provider_dispatch;
pub mod request_id;
pub(crate) mod request_log;
pub(crate) mod state;
pub mod site_guard;

pub use auth::client_auth_middleware;
pub use handlers::{event_logging_batch, proxy_chat_completions, proxy_count_tokens, proxy_flows, proxy_messages, proxy_models, proxy_responses, proxy_status, proxy_usage};
pub use kiro_handlers::{proxy_kiro_login_poll, proxy_kiro_login_start, proxy_kiro_social_exchange, proxy_kiro_social_start};
pub use state::AppState;
